#!/bin/bash

## For example: $0 /tmp/inputdownloading /tmp/preprocessing

## Checking args
if [ $# -ne 2 ]
then
  echo "Usage: $0 inputdownloading_path preprocessing_path"
  exit 1
fi

## args
IMAGE_DATASET=$1
IMAGE_PATHROW=$2
IMAGE_DATE=$3
INPUTDOWNLOADING_DIR_PATH=$4
PREPROCESSING_DIR_PATH=$5

METADATA_FILE_PATH=$PREPROCESSING_DIR_PATH/application.metadata
rm -rf $METADATA_FILE_PATH
touch $METADATA_FILE_PATH

B1_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B1.TIF")
B2_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B2.TIF")
B3_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B3.TIF")
B4_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B4.TIF")
B5_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B5.TIF")
B6_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6.TIF")
B6_VCID_1_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6_VCID_1.TIF")
B6_VCID_2_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B6_VCID_2.TIF")
B7_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B7.TIF")
B8_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B8.TIF")
B9_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B9.TIF")
B10_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B10.TIF")
B11_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_B11.TIF")
BQA_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_BQA.TIF")
STATION_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_station.csv")
MTL_INPUTDOWNLOADING_FILE_PATH=$(find $INPUTDOWNLOADING_DIR_PATH -iname "*_MTL.txt")

RASTER_ELEVATION_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "elevation.tif")
EVI_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_EVI.nc")
LAI_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_LAI.nc")
SAVI_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_SAVI.nc")
NDVI_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_NDVI.nc")
LSA_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_alb.nc")
LST_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_TS.nc")
RN_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_Rn.nc")
G_PREPROCESSING_FILE_PATH=$(find $PREPROCESSING_DIR_PATH -iname "*_G.nc")

CURRENT_DATE=$(date)

echo "#Preprocessing (default) Implementation Metadata" >> $METADATA_FILE_PATH
echo "$CURRENT_DATE # Date" >> $METADATA_FILE_PATH

echo "INPUT FILES" >> $METADATA_FILE_PATH >> $METADATA_FILE_PATH
echo "$B1_INPUTDOWNLOADING_FILE_PATH # Band 1 from image" >> $METADATA_FILE_PATH
echo "$B2_INPUTDOWNLOADING_FILE_PATH # Band 2 from image" >> $METADATA_FILE_PATH
echo "$B3_INPUTDOWNLOADING_FILE_PATH # Band 3 from image" >> $METADATA_FILE_PATH
echo "$B4_INPUTDOWNLOADING_FILE_PATH # Band 4 from image" >> $METADATA_FILE_PATH
echo "$B5_INPUTDOWNLOADING_FILE_PATH # Band 5 from image" >> $METADATA_FILE_PATH
if [ $IMAGE_DATASET == "landsat_5" ] || [ $IMAGE_DATASET == "landsat_8" ]
then
  echo "$B6_INPUTDOWNLOADING_FILE_PATH # Band 6 from image" >> $METADATA_FILE_PATH
fi
if [ $IMAGE_DATASET == "landsat_7" ]
then
  echo "$B6_VCID_1_INPUTDOWNLOADING_FILE_PATH # Band 6 VCID 1 from image" >> $METADATA_FILE_PATH
  echo "$B6_VCID_2_INPUTDOWNLOADING_FILE_PATH # Band 6 VCID 2 from image" >> $METADATA_FILE_PATH
fi
echo "$B7_INPUTDOWNLOADING_FILE_PATH # Band 7 from image" >> $METADATA_FILE_PATH
if [ $IMAGE_DATASET == "landsat_7" ]
then
  echo "$B8_INPUTDOWNLOADING_FILE_PATH # Band 8 from image" >> $METADATA_FILE_PATH
fi
if [ $IMAGE_DATASET == "landsat_8" ]
then
  echo "$B8_INPUTDOWNLOADING_FILE_PATH # Band 8 from image" >> $METADATA_FILE_PATH
  echo "$B9_INPUTDOWNLOADING_FILE_PATH # Band 9 from image" >> $METADATA_FILE_PATH
  echo "$B10_INPUTDOWNLOADING_FILE_PATH # Band 10 from image" >> $METADATA_FILE_PATH
  echo "$B11_INPUTDOWNLOADING_FILE_PATH # Band 11 from image" >> $METADATA_FILE_PATH
fi
echo "$BQA_INPUTDOWNLOADING_FILE_PATH # Band QA from image" >> $METADATA_FILE_PATH
echo "$MTL_INPUTDOWNLOADING_FILE_PATH # MTL from image" >> $METADATA_FILE_PATH
echo "$STATION_INPUTDOWNLOADING_FILE_PATH # Station data from image" >> $METADATA_FILE_PATH

echo "OUTPUT FILES" >> $METADATA_FILE_PATH
echo "$RASTER_ELEVATION_PREPROCESSING_FILE_PATH # Preprocessed Raster elevation data file path" >> $METADATA_FILE_PATH
echo "$EVI_PREPROCESSING_FILE_PATH # Enhanced Vegetation Index data file path" >> $METADATA_FILE_PATH
echo "$LAI_PREPROCESSING_FILE_PATH # Leaf Area Index data file path" >> $METADATA_FILE_PATH
echo "$SAVI_PREPROCESSING_FILE_PATH # Soil Adjusted Vegetation Index data file path" >> $METADATA_FILE_PATH
echo "$NDVI_PREPROCESSING_FILE_PATH # Normalized Different Vegetation Index data file path" >> $METADATA_FILE_PATH
echo "$LSA_PREPROCESSING_FILE_PATH # Land Surface Albedo data file path" >> $METADATA_FILE_PATH
echo "$LST_PREPROCESSING_FILE_PATH # Land Surface Temperature data file path" >> $METADATA_FILE_PATH
echo "$RN_PREPROCESSING_FILE_PATH # Net Radiation Balance data file path" >> $METADATA_FILE_PATH
echo "$G_PREPROCESSING_FILE_PATH # Ground Heat Flux data file path" >> $METADATA_FILE_PATH
